// Plan catalog loader with a module-level cache.
//
// Strategy (cost-optimized):
//   1. Fetch a single CDN-cached catalog.json from Firebase Storage. This is
//      ONE cheap request per visitor instead of N Firestore reads (one per
//      plan). The file is regenerated by `npm run migrate` / `build-catalog`.
//   2. If that fails (file missing, offline), fall back to a live Firestore
//      query of the `plans` collection.
//   3. If THAT fails too, fall back to BUILTIN_PLANS (empty by default).
//
// Plan images are Firebase Storage URLs, lazy-loaded by the browser as cards
// scroll into view — never bundled.

import { useEffect, useState } from "react";
import { collection, getDocs } from "firebase/firestore";
import { db } from "./firebase";
import { BUILTIN_PLANS } from "./floorPlans";

const BUCKET = import.meta.env.VITE_FIREBASE_STORAGE_BUCKET;
const CATALOG_URL = BUCKET
  ? `https://firebasestorage.googleapis.com/v0/b/${BUCKET}/o/${encodeURIComponent(
      "plans/catalog.json"
    )}?alt=media`
  : null;

let _cache = null;
let _inflight = null;

function normalize(data, id) {
  return {
    ...data,
    id,
    image: data.image || data.imageUrl || null,
    name: /^\d+$/.test(data.name) ? `Plan ${data.name}` : (data.name || id),
  };
}

async function fetchFromCatalog() {
  if (!CATALOG_URL) throw new Error("no bucket configured");
  const res = await fetch(CATALOG_URL, { cache: "default" });
  if (!res.ok) throw new Error(`catalog.json HTTP ${res.status}`);
  const data = await res.json();
  const plans = (data.plans || []).map((p) => normalize(p, p.id));
  if (!plans.length) throw new Error("catalog.json empty");
  return plans;
}

async function fetchFromFirestore() {
  const snap = await getDocs(collection(db, "plans"));
  const plans = snap.docs.map((d) => normalize(d.data(), d.id));
  plans.sort((a, b) =>
    (a.series || "").localeCompare(b.series || "") || (a.sqft || 0) - (b.sqft || 0)
  );
  return plans;
}

async function _load() {
  if (_cache) return _cache;
  if (_inflight) return _inflight;

  _inflight = (async () => {
    try {
      const remote = await fetchFromCatalog();
      _cache = [...BUILTIN_PLANS, ...remote];
      console.log(`[FrameUpNow] Loaded ${remote.length} plans from catalog.json (CDN).`);
    } catch (catalogErr) {
      console.warn("[FrameUpNow] catalog.json unavailable, querying Firestore:", catalogErr.message);
      try {
        const remote = await fetchFromFirestore();
        _cache = [...BUILTIN_PLANS, ...remote];
        console.log(`[FrameUpNow] Loaded ${remote.length} plans from Firestore (fallback).`);
      } catch (fsErr) {
        console.error("[FrameUpNow] Plan load failed:", fsErr.code, fsErr.message);
        _inflight = null; // allow a retry
        throw fsErr;
      }
    }
    return _cache;
  })();

  return _inflight;
}

// Kick off the fetch early (from main.jsx) so the catalog is warm by Step 3.
export function prefetchCatalog() {
  _load().catch(() => {}); // swallow — the hook surfaces the error to the UI
}

export function usePlansCatalog() {
  const [plans, setPlans] = useState(_cache ?? BUILTIN_PLANS);
  const [loading, setLoading] = useState(_cache === null);
  const [error, setError] = useState(null);
  const [reloadKey, setReloadKey] = useState(0);

  useEffect(() => {
    if (_cache !== null) {
      setPlans(_cache);
      setLoading(false);
      setError(null);
      return;
    }
    let stale = false;
    setLoading(true);
    setError(null);
    _load()
      .then((p) => { if (!stale) { setPlans(p); setLoading(false); } })
      .catch((e) => { if (!stale) { setError(e); setLoading(false); } });
    return () => { stale = true; };
  }, [reloadKey]);

  function getById(id) {
    return (plans ?? BUILTIN_PLANS).find((p) => p.id === id) ?? null;
  }

  // Retry after a failed load (used by the error state's "Try again" button).
  function reload() {
    _cache = null;
    _inflight = null;
    setReloadKey((k) => k + 1);
  }

  return { plans, loading, error, getById, reload };
}

export function invalidateCatalog() {
  _cache = null;
  _inflight = null;
}
